[package]
name = "erofs-sys"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
memmap2 = "0.9.4" # For Testing the Memory Backed Filesystem.

[features]
default = ["alloc"]
alloc = []
